# Generated by Django 3.2.4 on 2022-11-09 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yfcases', '0011_auto_20211104_1557'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finaldecision',
            name='finalDecisionRemark',
            field=models.CharField(blank=True, max_length=3000, null=True, verbose_name='備註'),
        ),
    ]
