# Generated by Django 3.2.4 on 2023-06-08 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yfcases', '0012_alter_finaldecision_finaldecisionremark'),
        ('yfcases', '0012_survey_surveymoneytviewlink_and_more'),
    ]

    operations = [
    ]
