# Generated by Django 3.2.4 on 2023-06-14 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yfcases', '0013_merge_20230608_2244'),
        ('yfcases', '0014_auction_auctioncasecountfirst_and_more'),
    ]

    operations = [
    ]
