# Generated by Django 5.0.2 on 2025-07-23 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yfcases', '0015_merge_20230615_0027'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coownerlitigation',
            name='coownerheir',
        ),
        migrations.RemoveField(
            model_name='coownerinfo',
            name='yfcase',
        ),
        migrations.DeleteModel(
            name='CoOwnerHeir',
        ),
        migrations.DeleteModel(
            name='CoOwnerLitigation',
        ),
        migrations.DeleteModel(
            name='CoOwnerInfo',
        ),
    ]
